services:
  bd_store:
    image: postgres:alpine
    container_name: bd_store
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - vol_postgres:/var/lib/postgresql/data

volumes:
  vol_postgres: